apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.training.lfs458.com
spec:
  group: training.lfs458.com
  scope: Cluster
  version: v1
  names:
    kind: CronTab
    singular: crontab
    plural: crontabs
    shortNames:
    - ct
