apiVersion: batch/v1
kind: Job
metadata: 
  name: sleepy
spec:
  activeDeadlineSeconds: 20
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: resting
        image: busybox
        command:
        - "/bin/sleep"
        args:
        - "10"
      restartPolicy: Never
