apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: production-role-binding
  namespace: production
roleRef:
  name: dev-prod
  kind: Role
  apiGroup: ""
subjects:
- name: DevDan
  kind: User
  apiGroup: ""
