apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: dev-prod
  namespace: production
rules:
- apiGroups: [ "" , "extensions" , "apps" ]
  resources: [ "deployments" , "replicasets" , "pods" ]
  verbs: [ "list" , "get" , "watch" ]  
